version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    restart: always

networks:
  default:
    external:
      name: servernetwork